"""create models

Revision ID: 658c45be7b24
Revises: 
Create Date: 2024-05-12 17:51:43.441588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658c45be7b24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bourse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_transaction', sa.Integer(), nullable=True),
    sa.Column('final_price', sa.Integer(), nullable=True),
    sa.Column('first_price', sa.Integer(), nullable=True),
    sa.Column('yesterday_price', sa.Integer(), nullable=True),
    sa.Column('transactions_number', sa.Integer(), nullable=True),
    sa.Column('volume_transaction', sa.Integer(), nullable=True),
    sa.Column('transaction_value', sa.Integer(), nullable=True),
    sa.Column('market_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_number', sa.Integer(), nullable=True),
    sa.Column('buy_number', sa.Integer(), nullable=True),
    sa.Column('sales_valume', sa.Integer(), nullable=True),
    sa.Column('buy_valume', sa.Integer(), nullable=True),
    sa.Column('sales', sa.Integer(), nullable=True),
    sa.Column('buy', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    op.drop_table('Bourse')
    # ### end Alembic commands ###
